apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: openai_test_mcp_ollama
  labels:
    app: testapp_mcp_ollama
spec:
  model: openai/rits/meta-llama/llama-3-3-70b-instruct
  description: test
  instructions: You are a helpful agent. Respond to the users question, making use of any required tools
  framework: openai
  mode: local

